version: '3'

services:
  
  ws_db:
    container_name: db
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./weather_service/.env
    ports:
      - 5432:5432

  ws_rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  weather_service:
    container_name: weather_service
    build:
      context: ./weather_service
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    depends_on:
      - ws_db

  ws_celery:
    container_name: celery
    build:
      context: ./weather_service
    command: celery -A weather_service worker
    volumes:
      - ./:/usr/src/
    env_file:
      - ./weather_service/.env
    depends_on:
      - ws_db
      - ws_rabbitmq

  ws_flower:
    container_name: flower
    image: mher/flower
    command: celery flower --persistent=True
    ports:
      - 8888:8888
    env_file:
      - ./weather_service/.env
    depends_on:
      - ws_rabbitmq