version: '3'

services:
  
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./weather_service/.env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  django:
    build:
      context: ./weather_service
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    depends_on:
      - db

  celery:
    build:
      context: ./weather_service
    command: celery -A weather_service worker
    volumes:
      - ./:/usr/src/
    env_file:
      - ./weather_service/.env
    depends_on:
      - db
      - rabbitmq

  flower:
    image: mher/flower
    command: celery flower
    ports:
      - 8888:8888
    env_file:
      - ./weather_service/.env
    depends_on:
      - rabbitmq