version: '3'

services:
  
  weather_service:
    container_name: weather_service
    build:
      context: ./weather_service
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000