# Generated by Django 4.2.4 on 2023-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cities', models.JSONField()),
            ],
        ),
    ]
